name: Github Backup Repository

on:
  # 設置時に起動時刻を設定してください
  schedule:
    - cron: '0 15 * * *' # 毎日日本時間0時に実行
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable-workflow:
    uses: pj8/.github/.github/workflows/github-backup-repository.yml@main
    secrets:
      AWS_3RD_ROLE_ARN: ${{ secrets.AWS_3RD_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BACKUP_BUCKET_NAME: ${{ secrets.BACKUP_BUCKET_NAME }}
