name: Test dbdb scripts

on: push

jobs:
  dbdb-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install coreutils
      - name: Run dbdb tests
        run: |
          cd tests/macos
          /bin/bash mongodb-test.sh
          /bin/bash mysql-test.sh
          /bin/bash postgresql-test.sh
          /bin/bash redis-test.sh
