name: Test

on: push

jobs:
  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install macos dependencies
        run: |
          brew install coreutils
      - name: Run mongodb test
        run: |
          cd tests
          /bin/bash mongodb-test.sh
      - name: Run mysql test
        run: |
          cd tests
          /bin/bash mysql-test.sh
      - name: Run postgresql test
        run: |
          cd tests
          /bin/bash postgresql-test.sh
      - name: Run redis test
        run: |
          cd tests
          /bin/bash redis-test.sh
  test-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run mongodb test
        run: |
          cd tests
          /bin/bash mongodb-test.sh
      - name: Run mysql test
        run: |
          cd tests
          /bin/bash mysql-test.sh
      - name: Run postgresql test
        run: |
          cd tests
          /bin/bash postgresql-test.sh
      - name: Run redis test
        run: |
          cd tests
          /bin/bash redis-test.sh
