name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        test_script: [mongodb-test.sh, mysql-test.sh, postgresql-12-test.sh, postgresql-13-test.sh, redis-test.sh]
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          cd tests
          /bin/bash ${{ matrix.test_script }}
