name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        test_script: [
          mongodb-4.4.10.sh,
          mongodb-5.0.3.sh,
          mysql-8.0.41.sh,
          mysql-8.4.4.sh,
          postgresql-12.4.sh,
          postgresql-13.2.sh,
          redis-6.2.14.sh,
          redis-7.2.5.sh,
          memcached-1.6.31.sh
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        run: |
          cd tests

      - name: Run test
        run: |
          cd tests
          /bin/bash ${{ matrix.test_script }}
