name: Test dbdb scripts

on: push

jobs:
  dbdb-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install macos dependencies
        if: matrix.os == 'macos-11' || matrix.os == 'macos-12'
        run: |
          brew install coreutils
      - name: Run mongodb test
        run: |
          cd tests/macos
          /bin/bash mongodb-test.sh
      - name: Run mysql test
        run: |
          cd tests/macos
          /bin/bash mysql-test.sh
      - name: Run postgresql test
        run: |
          cd tests/macos
          /bin/bash postgresql-test.sh
      - name: Run redis test
        run: |
          cd tests/macos
          /bin/bash redis-test.sh
